"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "app/src/main/res/values/strings.xml",
    "translation": "app/src/main/res/values-%android_code%/strings.xml",
  },
  {
    "source": "app/src/main/res/values/initdb.xml",
    "translation": "app/src/main/res/values-%android_code%/initdb.xml",
  }
]

