## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=C\:\path\\to\\your\\file\\sdk


# =========================================================================
# SIGNING CONFIGURATION (Secure Release Build)
# =========================================================================
# To enable release builds without leaking your credentials on GitHub,
# ensure your 'local.properties' file (in the project root) contains:
signing.store.file=C\:\path\\to\\your\\file\\ammx.keystore
signing.store.password=storepassword
signing.key.alias=androiddebugkey
signing.key.password=password
# =========================================================================