-- Asset Classes
CREATE TABLE ASSETCLASS_V1 (
    'ID' INTEGER primary key,
    'PARENTID' INTEGER,
    'NAME' TEXT COLLATE NOCASE NOT NULL,
    'ALLOCATION' REAL,
    'SORTORDER' INTEGER
);

-- Asset Class / Stock link table
CREATE TABLE ASSETCLASS_STOCK_V1 (
    'ID' INTEGER primary key,
    'ASSETCLASSID' INTEGER NOT NULL,
    'STOCKSYMBOL' TEXT UNIQUE
);