SELECT CATEGORY_V1.CATEGID AS _id,
CATEGORY_V1.CATEGID,
CATEGORY_V1.CATEGNAME,
-1 AS SUBCATEGID,
NULL AS SUBCATEGNAME,
CATEGORY_V1.CATEGNAME AS CATEGSUBNAME
FROM CATEGORY_V1
WHERE PARENTID < 0

UNION ALL

SELECT SUBCATEGORY_V1.CATEGID AS _id,
CATEGORY_V1.CATEGID,
CATEGORY_V1.CATEGNAME,
SUBCATEGORY_V1.CATEGID as SUBCATEGID,
SUBCATEGORY_V1.CATEGNAME as SUBCATEGNAME,
CATEGORY_V1.CATEGNAME || CASE WHEN SUBCATEGORY_V1.CATEGNAME IS NOT NULL THEN ' : ' || SUBCATEGORY_V1.CATEGNAME ELSE '' END AS CATEGSUBNAME
FROM CATEGORY_V1
INNER JOIN CATEGORY_V1 as SUBCATEGORY_V1 ON CATEGORY_V1.CATEGID = SUBCATEGORY_V1.PARENTID
WHERE CATEGORY_V1.PARENTID < 0 and SUBCATEGORY_V1.PARENTID > 0
