DROP TABLE IF EXISTS "ACCOUNTLIST_V1";
CREATE TABLE IF NOT EXISTS "ACCOUNTLIST_V1" (
	"ACCOUNTID"	integer,
	"ACCOUNTNAME"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"ACCOUNTTYPE"	TEXT NOT NULL,
	"ACCOUNTNUM"	TEXT,
	"STATUS"	TEXT NOT NULL,
	"NOTES"	TEXT,
	"HELDAT"	TEXT,
	"WEBSITE"	TEXT,
	"CONTACTINFO"	TEXT,
	"ACCESSINFO"	TEXT,
	"INITIALBAL"	numeric,
	"INITIALDATE"	TEXT,
	"FAVORITEACCT"	TEXT NOT NULL,
	"CURRENCYID"	integer NOT NULL,
	"STATEMENTLOCKED"	integer,
	"STATEMENTDATE"	TEXT,
	"MINIMUMBALANCE"	numeric,
	"CREDITLIMIT"	numeric,
	"INTERESTRATE"	numeric,
	"PAYMENTDUEDATE"	text,
	"MINIMUMPAYMENT"	numeric,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("ACCOUNTID")
);
DROP TABLE IF EXISTS "ASSETS_V1";
CREATE TABLE IF NOT EXISTS "ASSETS_V1" (
	"ASSETID"	integer,
	"STARTDATE"	TEXT NOT NULL,
	"ASSETNAME"	TEXT NOT NULL COLLATE NOCASE,
	"ASSETSTATUS"	TEXT,
	"CURRENCYID"	integer,
	"VALUECHANGEMODE"	TEXT,
	"VALUE"	numeric,
	"VALUECHANGE"	TEXT,
	"NOTES"	TEXT,
	"VALUECHANGERATE"	numeric,
	"ASSETTYPE"	TEXT,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("ASSETID")
);
DROP TABLE IF EXISTS "BILLSDEPOSITS_V1";
CREATE TABLE IF NOT EXISTS "BILLSDEPOSITS_V1" (
	"BDID"	integer,
	"ACCOUNTID"	integer NOT NULL,
	"TOACCOUNTID"	integer,
	"PAYEEID"	integer NOT NULL,
	"TRANSCODE"	TEXT NOT NULL,
	"TRANSAMOUNT"	numeric NOT NULL,
	"STATUS"	TEXT,
	"TRANSACTIONNUMBER"	TEXT,
	"NOTES"	TEXT,
	"CATEGID"	integer,
	"TRANSDATE"	TEXT,
	"FOLLOWUPID"	integer,
	"TOTRANSAMOUNT"	numeric,
	"REPEATS"	integer,
	"NEXTOCCURRENCEDATE"	TEXT,
	"NUMOCCURRENCES"	integer,
	"COLOR"	integer DEFAULT -1,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("BDID")
);
DROP TABLE IF EXISTS "BUDGETSPLITTRANSACTIONS_V1";
CREATE TABLE IF NOT EXISTS "BUDGETSPLITTRANSACTIONS_V1" (
	"SPLITTRANSID"	integer,
	"TRANSID"	integer NOT NULL,
	"CATEGID"	integer,
	"SPLITTRANSAMOUNT"	numeric,
	"NOTES"	TEXT,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("SPLITTRANSID")
);
DROP TABLE IF EXISTS "BUDGETTABLE_V1";
CREATE TABLE IF NOT EXISTS "BUDGETTABLE_V1" (
	"BUDGETENTRYID"	integer,
	"BUDGETYEARID"	integer,
	"CATEGID"	integer,
	"PERIOD"	TEXT NOT NULL,
	"AMOUNT"	numeric NOT NULL,
	"NOTES"	TEXT,
	"ACTIVE"	integer,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("BUDGETENTRYID")
);
DROP TABLE IF EXISTS "BUDGETYEAR_V1";
CREATE TABLE IF NOT EXISTS "BUDGETYEAR_V1" (
	"BUDGETYEARID"	integer,
	"BUDGETYEARNAME"	TEXT NOT NULL UNIQUE,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("BUDGETYEARID")
);
DROP TABLE IF EXISTS "CATEGORY_V1";
CREATE TABLE IF NOT EXISTS "CATEGORY_V1" (
	"CATEGID"	INTEGER,
	"CATEGNAME"	TEXT NOT NULL COLLATE NOCASE,
	"ACTIVE"	INTEGER,
	"PARENTID"	INTEGER,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("CATEGID"),
	UNIQUE("CATEGNAME","PARENTID")
);
DROP TABLE IF EXISTS "CHECKINGACCOUNT_V1";
CREATE TABLE IF NOT EXISTS "CHECKINGACCOUNT_V1" (
	"TRANSID"	integer,
	"ACCOUNTID"	integer NOT NULL,
	"TOACCOUNTID"	integer,
	"PAYEEID"	integer NOT NULL,
	"TRANSCODE"	TEXT NOT NULL,
	"TRANSAMOUNT"	numeric NOT NULL,
	"STATUS"	TEXT,
	"TRANSACTIONNUMBER"	TEXT,
	"NOTES"	TEXT,
	"CATEGID"	integer,
	"TRANSDATE"	TEXT,
	"LASTUPDATEDTIME"	TEXT,
	"DELETEDTIME"	TEXT,
	"FOLLOWUPID"	integer,
	"TOTRANSAMOUNT"	numeric,
	"COLOR"	integer DEFAULT -1,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("TRANSID")
);
DROP TABLE IF EXISTS "CURRENCYHISTORY_V1";
CREATE TABLE IF NOT EXISTS "CURRENCYHISTORY_V1" (
	"CURRHISTID"	INTEGER,
	"CURRENCYID"	INTEGER NOT NULL,
	"CURRDATE"	TEXT NOT NULL,
	"CURRVALUE"	NUMERIC NOT NULL,
	"CURRUPDTYPE"	INTEGER,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("CURRHISTID"),
	UNIQUE("CURRENCYID","CURRDATE")
);
DROP TABLE IF EXISTS "CURRENCYFORMATS_V1";
CREATE TABLE IF NOT EXISTS "CURRENCYFORMATS_V1" (
	"CURRENCYID"	integer,
	"CURRENCYNAME"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"PFX_SYMBOL"	TEXT,
	"SFX_SYMBOL"	TEXT,
	"DECIMAL_POINT"	TEXT,
	"GROUP_SEPARATOR"	TEXT,
	"UNIT_NAME"	TEXT COLLATE NOCASE,
	"CENT_NAME"	TEXT COLLATE NOCASE,
	"SCALE"	integer,
	"BASECONVRATE"	numeric,
	"CURRENCY_SYMBOL"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"CURRENCY_TYPE"	TEXT NOT NULL,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("CURRENCYID")
);
DROP TABLE IF EXISTS "INFOTABLE_V1";
CREATE TABLE IF NOT EXISTS "INFOTABLE_V1" (
	"INFOID"	integer NOT NULL,
	"INFONAME"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"INFOVALUE"	TEXT NOT NULL,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("INFOID")
);
DROP TABLE IF EXISTS "PAYEE_V1";
CREATE TABLE IF NOT EXISTS "PAYEE_V1" (
	"PAYEEID"	integer,
	"PAYEENAME"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"CATEGID"	integer,
	"NUMBER"	TEXT,
	"WEBSITE"	TEXT,
	"NOTES"	TEXT,
	"ACTIVE"	integer,
	"PATTERN"	TEXT DEFAULT '',
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("PAYEEID")
);
DROP TABLE IF EXISTS "SPLITTRANSACTIONS_V1";
CREATE TABLE IF NOT EXISTS "SPLITTRANSACTIONS_V1" (
	"SPLITTRANSID"	integer,
	"TRANSID"	integer NOT NULL,
	"CATEGID"	integer,
	"SPLITTRANSAMOUNT"	numeric,
	"NOTES"	TEXT,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("SPLITTRANSID")
);
DROP TABLE IF EXISTS "STOCK_V1";
CREATE TABLE IF NOT EXISTS "STOCK_V1" (
	"STOCKID"	integer,
	"HELDAT"	integer,
	"PURCHASEDATE"	TEXT NOT NULL,
	"STOCKNAME"	TEXT NOT NULL COLLATE NOCASE,
	"SYMBOL"	TEXT,
	"NUMSHARES"	numeric,
	"PURCHASEPRICE"	numeric NOT NULL,
	"NOTES"	TEXT,
	"CURRENTPRICE"	numeric NOT NULL,
	"VALUE"	numeric,
	"COMMISSION"	numeric,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("STOCKID")
);
DROP TABLE IF EXISTS "STOCKHISTORY_V1";
CREATE TABLE IF NOT EXISTS "STOCKHISTORY_V1" (
	"HISTID"	integer,
	"SYMBOL"	TEXT NOT NULL,
	"DATE"	TEXT NOT NULL,
	"VALUE"	numeric NOT NULL,
	"UPDTYPE"	integer,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("HISTID"),
	UNIQUE("SYMBOL","DATE")
);
DROP TABLE IF EXISTS "REPORT_V1";
CREATE TABLE IF NOT EXISTS "REPORT_V1" (
	"REPORTID"	integer NOT NULL,
	"REPORTNAME"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"GROUPNAME"	TEXT COLLATE NOCASE,
	"ACTIVE"	integer,
	"SQLCONTENT"	TEXT,
	"LUACONTENT"	TEXT,
	"TEMPLATECONTENT"	TEXT,
	"DESCRIPTION"	TEXT,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("REPORTID")
);
DROP TABLE IF EXISTS "ATTACHMENT_V1";
CREATE TABLE IF NOT EXISTS "ATTACHMENT_V1" (
	"ATTACHMENTID"	INTEGER NOT NULL,
	"REFTYPE"	TEXT NOT NULL,
	"REFID"	INTEGER NOT NULL,
	"DESCRIPTION"	TEXT COLLATE NOCASE,
	"FILENAME"	TEXT NOT NULL COLLATE NOCASE,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("ATTACHMENTID")
);
DROP TABLE IF EXISTS "CUSTOMFIELD_V1";
CREATE TABLE IF NOT EXISTS "CUSTOMFIELD_V1" (
	"FIELDID"	INTEGER NOT NULL,
	"REFTYPE"	TEXT NOT NULL,
	"DESCRIPTION"	TEXT COLLATE NOCASE,
	"TYPE"	TEXT NOT NULL,
	"PROPERTIES"	TEXT NOT NULL,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("FIELDID")
);
DROP TABLE IF EXISTS "CUSTOMFIELDDATA_V1";
CREATE TABLE IF NOT EXISTS "CUSTOMFIELDDATA_V1" (
	"FIELDATADID"	INTEGER NOT NULL,
	"FIELDID"	INTEGER NOT NULL,
	"REFID"	INTEGER NOT NULL,
	"CONTENT"	TEXT,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("FIELDATADID"),
	UNIQUE("FIELDID","REFID")
);
DROP TABLE IF EXISTS "TRANSLINK_V1";
CREATE TABLE IF NOT EXISTS "TRANSLINK_V1" (
	"TRANSLINKID"	integer NOT NULL,
	"CHECKINGACCOUNTID"	integer NOT NULL,
	"LINKTYPE"	TEXT NOT NULL,
	"LINKRECORDID"	integer NOT NULL,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("TRANSLINKID")
);
DROP TABLE IF EXISTS "SHAREINFO_V1";
CREATE TABLE IF NOT EXISTS "SHAREINFO_V1" (
	"SHAREINFOID"	integer NOT NULL,
	"CHECKINGACCOUNTID"	integer NOT NULL,
	"SHARENUMBER"	numeric,
	"SHAREPRICE"	numeric,
	"SHARECOMMISSION"	numeric,
	"SHARELOT"	TEXT,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("SHAREINFOID")
);
DROP TABLE IF EXISTS "TAG_V1";
CREATE TABLE IF NOT EXISTS "TAG_V1" (
	"TAGID"	INTEGER,
	"TAGNAME"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"ACTIVE"	INTEGER,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("TAGID")
);
DROP TABLE IF EXISTS "TAGLINK_V1";
CREATE TABLE IF NOT EXISTS "TAGLINK_V1" (
	"TAGLINKID"	INTEGER,
	"REFTYPE"	TEXT NOT NULL,
	"REFID"	INTEGER NOT NULL,
	"TAGID"	INTEGER NOT NULL,
	"pb_id"	TEXT,
	"pb_updated_at"	TEXT,
	"pb_is_dirty"	INTEGER DEFAULT 0,
	PRIMARY KEY("TAGLINKID"),
	UNIQUE("REFTYPE","REFID","TAGID"),
	FOREIGN KEY("TAGID") REFERENCES "TAG_V1"("TAGID")
);
DROP TABLE IF EXISTS "pb_DELETED_RECORDS_LOG";
CREATE TABLE IF NOT EXISTS "pb_DELETED_RECORDS_LOG" (
	"id"	INTEGER,
	"table_name"	TEXT NOT NULL,
	"pb_id"	TEXT NOT NULL,
	"deleted_at"	TEXT DEFAULT (STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')),
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP INDEX IF EXISTS "IDX_ACCOUNTLIST_ACCOUNTTYPE";
CREATE INDEX IF NOT EXISTS "IDX_ACCOUNTLIST_ACCOUNTTYPE" ON "ACCOUNTLIST_V1" (
	"ACCOUNTTYPE"
);
DROP INDEX IF EXISTS "IDX_ASSETS_ASSETTYPE";
CREATE INDEX IF NOT EXISTS "IDX_ASSETS_ASSETTYPE" ON "ASSETS_V1" (
	"ASSETTYPE"
);
DROP INDEX IF EXISTS "IDX_BILLSDEPOSITS_ACCOUNT";
CREATE INDEX IF NOT EXISTS "IDX_BILLSDEPOSITS_ACCOUNT" ON "BILLSDEPOSITS_V1" (
	"ACCOUNTID",
	"TOACCOUNTID"
);
DROP INDEX IF EXISTS "IDX_BUDGETSPLITTRANSACTIONS_TRANSID";
CREATE INDEX IF NOT EXISTS "IDX_BUDGETSPLITTRANSACTIONS_TRANSID" ON "BUDGETSPLITTRANSACTIONS_V1" (
	"TRANSID"
);
DROP INDEX IF EXISTS "IDX_BUDGETTABLE_BUDGETYEARID";
CREATE INDEX IF NOT EXISTS "IDX_BUDGETTABLE_BUDGETYEARID" ON "BUDGETTABLE_V1" (
	"BUDGETYEARID"
);
DROP INDEX IF EXISTS "IDX_BUDGETYEAR_BUDGETYEARNAME";
CREATE INDEX IF NOT EXISTS "IDX_BUDGETYEAR_BUDGETYEARNAME" ON "BUDGETYEAR_V1" (
	"BUDGETYEARNAME"
);
DROP INDEX IF EXISTS "IDX_CATEGORY_CATEGNAME";
CREATE INDEX IF NOT EXISTS "IDX_CATEGORY_CATEGNAME" ON "CATEGORY_V1" (
	"CATEGNAME"
);
DROP INDEX IF EXISTS "IDX_CATEGORY_CATEGNAME_PARENTID";
CREATE INDEX IF NOT EXISTS "IDX_CATEGORY_CATEGNAME_PARENTID" ON "CATEGORY_V1" (
	"CATEGNAME",
	"PARENTID"
);
DROP INDEX IF EXISTS "IDX_CHECKINGACCOUNT_ACCOUNT";
CREATE INDEX IF NOT EXISTS "IDX_CHECKINGACCOUNT_ACCOUNT" ON "CHECKINGACCOUNT_V1" (
	"ACCOUNTID",
	"TOACCOUNTID"
);
DROP INDEX IF EXISTS "IDX_CHECKINGACCOUNT_TRANSDATE";
CREATE INDEX IF NOT EXISTS "IDX_CHECKINGACCOUNT_TRANSDATE" ON "CHECKINGACCOUNT_V1" (
	"TRANSDATE"
);
DROP INDEX IF EXISTS "IDX_CURRENCYHISTORY_CURRENCYID_CURRDATE";
CREATE INDEX IF NOT EXISTS "IDX_CURRENCYHISTORY_CURRENCYID_CURRDATE" ON "CURRENCYHISTORY_V1" (
	"CURRENCYID",
	"CURRDATE"
);
DROP INDEX IF EXISTS "IDX_CURRENCYFORMATS_SYMBOL";
CREATE INDEX IF NOT EXISTS "IDX_CURRENCYFORMATS_SYMBOL" ON "CURRENCYFORMATS_V1" (
	"CURRENCY_SYMBOL"
);
DROP INDEX IF EXISTS "IDX_INFOTABLE_INFONAME";
CREATE INDEX IF NOT EXISTS "IDX_INFOTABLE_INFONAME" ON "INFOTABLE_V1" (
	"INFONAME"
);
DROP INDEX IF EXISTS "IDX_PAYEE_INFONAME";
CREATE INDEX IF NOT EXISTS "IDX_PAYEE_INFONAME" ON "PAYEE_V1" (
	"PAYEENAME"
);
DROP INDEX IF EXISTS "IDX_SPLITTRANSACTIONS_TRANSID";
CREATE INDEX IF NOT EXISTS "IDX_SPLITTRANSACTIONS_TRANSID" ON "SPLITTRANSACTIONS_V1" (
	"TRANSID"
);
DROP INDEX IF EXISTS "IDX_STOCK_HELDAT";
CREATE INDEX IF NOT EXISTS "IDX_STOCK_HELDAT" ON "STOCK_V1" (
	"HELDAT"
);
DROP INDEX IF EXISTS "IDX_STOCKHISTORY_SYMBOL";
CREATE INDEX IF NOT EXISTS "IDX_STOCKHISTORY_SYMBOL" ON "STOCKHISTORY_V1" (
	"SYMBOL"
);
DROP INDEX IF EXISTS "INDEX_REPORT_NAME";
CREATE INDEX IF NOT EXISTS "INDEX_REPORT_NAME" ON "REPORT_V1" (
	"REPORTNAME"
);
DROP INDEX IF EXISTS "IDX_ATTACHMENT_REF";
CREATE INDEX IF NOT EXISTS "IDX_ATTACHMENT_REF" ON "ATTACHMENT_V1" (
	"REFTYPE",
	"REFID"
);
DROP INDEX IF EXISTS "IDX_CUSTOMFIELD_REF";
CREATE INDEX IF NOT EXISTS "IDX_CUSTOMFIELD_REF" ON "CUSTOMFIELD_V1" (
	"REFTYPE"
);
DROP INDEX IF EXISTS "IDX_CUSTOMFIELDDATA_REF";
CREATE INDEX IF NOT EXISTS "IDX_CUSTOMFIELDDATA_REF" ON "CUSTOMFIELDDATA_V1" (
	"FIELDID",
	"REFID"
);
DROP INDEX IF EXISTS "IDX_LINKRECORD";
CREATE INDEX IF NOT EXISTS "IDX_LINKRECORD" ON "TRANSLINK_V1" (
	"LINKTYPE",
	"LINKRECORDID"
);
DROP INDEX IF EXISTS "IDX_CHECKINGACCOUNT";
CREATE INDEX IF NOT EXISTS "IDX_CHECKINGACCOUNT" ON "TRANSLINK_V1" (
	"CHECKINGACCOUNTID"
);
DROP INDEX IF EXISTS "IDX_SHAREINFO";
CREATE INDEX IF NOT EXISTS "IDX_SHAREINFO" ON "SHAREINFO_V1" (
	"CHECKINGACCOUNTID"
);
DROP INDEX IF EXISTS "IDX_TAGNAME";
CREATE INDEX IF NOT EXISTS "IDX_TAGNAME" ON "TAG_V1" (
	"TAGNAME"
);
DROP INDEX IF EXISTS "IDX_TAGLINK";
CREATE INDEX IF NOT EXISTS "IDX_TAGLINK" ON "TAGLINK_V1" (
	"REFTYPE",
	"REFID",
	"TAGID"
);
DROP INDEX IF EXISTS "IDX_ACCOUNTLIST_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_ACCOUNTLIST_UNIQUE_PB_ID" ON "ACCOUNTLIST_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_ASSETS_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_ASSETS_UNIQUE_PB_ID" ON "ASSETS_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_BILLSDEPOSITS_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_BILLSDEPOSITS_UNIQUE_PB_ID" ON "BILLSDEPOSITS_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_BUDGETSPLITTRANSACTIONS_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_BUDGETSPLITTRANSACTIONS_UNIQUE_PB_ID" ON "BUDGETSPLITTRANSACTIONS_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_BUDGETTABLE_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_BUDGETTABLE_UNIQUE_PB_ID" ON "BUDGETTABLE_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_BUDGETYEAR_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_BUDGETYEAR_UNIQUE_PB_ID" ON "BUDGETYEAR_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_CATEGORY_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_CATEGORY_UNIQUE_PB_ID" ON "CATEGORY_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_CHECKINGACCOUNT_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_CHECKINGACCOUNT_UNIQUE_PB_ID" ON "CHECKINGACCOUNT_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_CURRENCYHISTORY_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_CURRENCYHISTORY_UNIQUE_PB_ID" ON "CURRENCYHISTORY_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_CURRENCYFORMATS_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_CURRENCYFORMATS_UNIQUE_PB_ID" ON "CURRENCYFORMATS_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_INFOTABLE_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_INFOTABLE_UNIQUE_PB_ID" ON "INFOTABLE_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_PAYEE_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_PAYEE_UNIQUE_PB_ID" ON "PAYEE_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_SPLITTRANSACTIONS_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_SPLITTRANSACTIONS_UNIQUE_PB_ID" ON "SPLITTRANSACTIONS_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_STOCK_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_STOCK_UNIQUE_PB_ID" ON "STOCK_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_STOCKHISTORY_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_STOCKHISTORY_UNIQUE_PB_ID" ON "STOCKHISTORY_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_REPORT_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_REPORT_UNIQUE_PB_ID" ON "REPORT_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_ATTACHMENT_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_ATTACHMENT_UNIQUE_PB_ID" ON "ATTACHMENT_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_CUSTOMFIELD_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_CUSTOMFIELD_UNIQUE_PB_ID" ON "CUSTOMFIELD_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_CUSTOMFIELDDATA_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_CUSTOMFIELDDATA_UNIQUE_PB_ID" ON "CUSTOMFIELDDATA_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_TRANSLINK_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_TRANSLINK_UNIQUE_PB_ID" ON "TRANSLINK_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_SHAREINFO_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_SHAREINFO_UNIQUE_PB_ID" ON "SHAREINFO_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_TAG_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_TAG_UNIQUE_PB_ID" ON "TAG_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP INDEX IF EXISTS "IDX_TAGLINK_UNIQUE_PB_ID";
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_TAGLINK_UNIQUE_PB_ID" ON "TAGLINK_V1" (
	"pb_id"
) WHERE "pb_id" IS NOT NULL;
DROP TRIGGER IF EXISTS "TRG_INFOTABLE_V1_INSERT";
CREATE TRIGGER TRG_INFOTABLE_V1_INSERT AFTER INSERT ON INFOTABLE_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE INFOTABLE_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE INFOID = NEW.INFOID;
            END;
DROP TRIGGER IF EXISTS "TRG_INFOTABLE_V1_UPDATE";
CREATE TRIGGER TRG_INFOTABLE_V1_UPDATE AFTER UPDATE ON INFOTABLE_V1
            FOR EACH ROW WHEN ((NEW.INFONAME IS NOT OLD.INFONAME OR NEW.INFOVALUE IS NOT OLD.INFOVALUE) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE INFOTABLE_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE INFOID = NEW.INFOID;
            END;
DROP TRIGGER IF EXISTS "TRG_INFOTABLE_V1_DELETE";
CREATE TRIGGER TRG_INFOTABLE_V1_DELETE AFTER DELETE ON INFOTABLE_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('INFOTABLE_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_CURRENCYFORMATS_V1_INSERT";
CREATE TRIGGER TRG_CURRENCYFORMATS_V1_INSERT AFTER INSERT ON CURRENCYFORMATS_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE CURRENCYFORMATS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE CURRENCYID = NEW.CURRENCYID;
            END;
DROP TRIGGER IF EXISTS "TRG_CURRENCYFORMATS_V1_UPDATE";
CREATE TRIGGER TRG_CURRENCYFORMATS_V1_UPDATE AFTER UPDATE ON CURRENCYFORMATS_V1
            FOR EACH ROW WHEN ((NEW.CURRENCYNAME IS NOT OLD.CURRENCYNAME OR NEW.PFX_SYMBOL IS NOT OLD.PFX_SYMBOL OR NEW.SFX_SYMBOL IS NOT OLD.SFX_SYMBOL OR NEW.DECIMAL_POINT IS NOT OLD.DECIMAL_POINT OR NEW.GROUP_SEPARATOR IS NOT OLD.GROUP_SEPARATOR OR NEW.UNIT_NAME IS NOT OLD.UNIT_NAME OR NEW.CENT_NAME IS NOT OLD.CENT_NAME OR NEW.SCALE IS NOT OLD.SCALE OR NEW.BASECONVRATE IS NOT OLD.BASECONVRATE OR NEW.CURRENCY_SYMBOL IS NOT OLD.CURRENCY_SYMBOL OR NEW.CURRENCY_TYPE IS NOT OLD.CURRENCY_TYPE) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE CURRENCYFORMATS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE CURRENCYID = NEW.CURRENCYID;
            END;
DROP TRIGGER IF EXISTS "TRG_CURRENCYFORMATS_V1_DELETE";
CREATE TRIGGER TRG_CURRENCYFORMATS_V1_DELETE AFTER DELETE ON CURRENCYFORMATS_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('CURRENCYFORMATS_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_CATEGORY_V1_INSERT";
CREATE TRIGGER TRG_CATEGORY_V1_INSERT AFTER INSERT ON CATEGORY_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE CATEGORY_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE CATEGID = NEW.CATEGID;
            END;
DROP TRIGGER IF EXISTS "TRG_CATEGORY_V1_UPDATE";
CREATE TRIGGER TRG_CATEGORY_V1_UPDATE AFTER UPDATE ON CATEGORY_V1
            FOR EACH ROW WHEN ((NEW.CATEGNAME IS NOT OLD.CATEGNAME OR NEW.ACTIVE IS NOT OLD.ACTIVE OR NEW.PARENTID IS NOT OLD.PARENTID) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE CATEGORY_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE CATEGID = NEW.CATEGID;
            END;
DROP TRIGGER IF EXISTS "TRG_CATEGORY_V1_DELETE";
CREATE TRIGGER TRG_CATEGORY_V1_DELETE AFTER DELETE ON CATEGORY_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('CATEGORY_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_TAG_V1_INSERT";
CREATE TRIGGER TRG_TAG_V1_INSERT AFTER INSERT ON TAG_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE TAG_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TAGID = NEW.TAGID;
            END;
DROP TRIGGER IF EXISTS "TRG_TAG_V1_UPDATE";
CREATE TRIGGER TRG_TAG_V1_UPDATE AFTER UPDATE ON TAG_V1
            FOR EACH ROW WHEN ((NEW.TAGNAME IS NOT OLD.TAGNAME OR NEW.ACTIVE IS NOT OLD.ACTIVE) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE TAG_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TAGID = NEW.TAGID;
            END;
DROP TRIGGER IF EXISTS "TRG_TAG_V1_DELETE";
CREATE TRIGGER TRG_TAG_V1_DELETE AFTER DELETE ON TAG_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('TAG_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_PAYEE_V1_INSERT";
CREATE TRIGGER TRG_PAYEE_V1_INSERT AFTER INSERT ON PAYEE_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE PAYEE_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE PAYEEID = NEW.PAYEEID;
            END;
DROP TRIGGER IF EXISTS "TRG_PAYEE_V1_UPDATE";
CREATE TRIGGER TRG_PAYEE_V1_UPDATE AFTER UPDATE ON PAYEE_V1
            FOR EACH ROW WHEN ((NEW.PAYEENAME IS NOT OLD.PAYEENAME OR NEW.CATEGID IS NOT OLD.CATEGID OR NEW.NUMBER IS NOT OLD.NUMBER OR NEW.WEBSITE IS NOT OLD.WEBSITE OR NEW.NOTES IS NOT OLD.NOTES OR NEW.ACTIVE IS NOT OLD.ACTIVE OR NEW.PATTERN IS NOT OLD.PATTERN) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE PAYEE_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE PAYEEID = NEW.PAYEEID;
            END;
DROP TRIGGER IF EXISTS "TRG_PAYEE_V1_DELETE";
CREATE TRIGGER TRG_PAYEE_V1_DELETE AFTER DELETE ON PAYEE_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('PAYEE_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_ACCOUNTLIST_V1_INSERT";
CREATE TRIGGER TRG_ACCOUNTLIST_V1_INSERT AFTER INSERT ON ACCOUNTLIST_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE ACCOUNTLIST_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE ACCOUNTID = NEW.ACCOUNTID;
            END;
DROP TRIGGER IF EXISTS "TRG_ACCOUNTLIST_V1_UPDATE";
CREATE TRIGGER TRG_ACCOUNTLIST_V1_UPDATE AFTER UPDATE ON ACCOUNTLIST_V1
            FOR EACH ROW WHEN ((NEW.ACCOUNTNAME IS NOT OLD.ACCOUNTNAME OR NEW.ACCOUNTTYPE IS NOT OLD.ACCOUNTTYPE OR NEW.ACCOUNTNUM IS NOT OLD.ACCOUNTNUM OR NEW.STATUS IS NOT OLD.STATUS OR NEW.NOTES IS NOT OLD.NOTES OR NEW.HELDAT IS NOT OLD.HELDAT OR NEW.WEBSITE IS NOT OLD.WEBSITE OR NEW.CONTACTINFO IS NOT OLD.CONTACTINFO OR NEW.ACCESSINFO IS NOT OLD.ACCESSINFO OR NEW.INITIALBAL IS NOT OLD.INITIALBAL OR NEW.INITIALDATE IS NOT OLD.INITIALDATE OR NEW.FAVORITEACCT IS NOT OLD.FAVORITEACCT OR NEW.CURRENCYID IS NOT OLD.CURRENCYID OR NEW.STATEMENTLOCKED IS NOT OLD.STATEMENTLOCKED OR NEW.STATEMENTDATE IS NOT OLD.STATEMENTDATE OR NEW.MINIMUMBALANCE IS NOT OLD.MINIMUMBALANCE OR NEW.CREDITLIMIT IS NOT OLD.CREDITLIMIT OR NEW.INTERESTRATE IS NOT OLD.INTERESTRATE OR NEW.PAYMENTDUEDATE IS NOT OLD.PAYMENTDUEDATE OR NEW.MINIMUMPAYMENT IS NOT OLD.MINIMUMPAYMENT) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE ACCOUNTLIST_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE ACCOUNTID = NEW.ACCOUNTID;
            END;
DROP TRIGGER IF EXISTS "TRG_ACCOUNTLIST_V1_DELETE";
CREATE TRIGGER TRG_ACCOUNTLIST_V1_DELETE AFTER DELETE ON ACCOUNTLIST_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('ACCOUNTLIST_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_ASSETS_V1_INSERT";
CREATE TRIGGER TRG_ASSETS_V1_INSERT AFTER INSERT ON ASSETS_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE ASSETS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE ASSETID = NEW.ASSETID;
            END;
DROP TRIGGER IF EXISTS "TRG_ASSETS_V1_UPDATE";
CREATE TRIGGER TRG_ASSETS_V1_UPDATE AFTER UPDATE ON ASSETS_V1
            FOR EACH ROW WHEN ((NEW.STARTDATE IS NOT OLD.STARTDATE OR NEW.ASSETNAME IS NOT OLD.ASSETNAME OR NEW.ASSETSTATUS IS NOT OLD.ASSETSTATUS OR NEW.CURRENCYID IS NOT OLD.CURRENCYID OR NEW.VALUECHANGEMODE IS NOT OLD.VALUECHANGEMODE OR NEW.VALUE IS NOT OLD.VALUE OR NEW.VALUECHANGE IS NOT OLD.VALUECHANGE OR NEW.NOTES IS NOT OLD.NOTES OR NEW.VALUECHANGERATE IS NOT OLD.VALUECHANGERATE OR NEW.ASSETTYPE IS NOT OLD.ASSETTYPE) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE ASSETS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE ASSETID = NEW.ASSETID;
            END;
DROP TRIGGER IF EXISTS "TRG_ASSETS_V1_DELETE";
CREATE TRIGGER TRG_ASSETS_V1_DELETE AFTER DELETE ON ASSETS_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('ASSETS_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_STOCK_V1_INSERT";
CREATE TRIGGER TRG_STOCK_V1_INSERT AFTER INSERT ON STOCK_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE STOCK_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE STOCKID = NEW.STOCKID;
            END;
DROP TRIGGER IF EXISTS "TRG_STOCK_V1_UPDATE";
CREATE TRIGGER TRG_STOCK_V1_UPDATE AFTER UPDATE ON STOCK_V1
            FOR EACH ROW WHEN ((NEW.HELDAT IS NOT OLD.HELDAT OR NEW.PURCHASEDATE IS NOT OLD.PURCHASEDATE OR NEW.STOCKNAME IS NOT OLD.STOCKNAME OR NEW.SYMBOL IS NOT OLD.SYMBOL OR NEW.NUMSHARES IS NOT OLD.NUMSHARES OR NEW.PURCHASEPRICE IS NOT OLD.PURCHASEPRICE OR NEW.NOTES IS NOT OLD.NOTES OR NEW.CURRENTPRICE IS NOT OLD.CURRENTPRICE OR NEW.VALUE IS NOT OLD.VALUE OR NEW.COMMISSION IS NOT OLD.COMMISSION) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE STOCK_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE STOCKID = NEW.STOCKID;
            END;
DROP TRIGGER IF EXISTS "TRG_STOCK_V1_DELETE";
CREATE TRIGGER TRG_STOCK_V1_DELETE AFTER DELETE ON STOCK_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('STOCK_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_CHECKINGACCOUNT_V1_INSERT";
CREATE TRIGGER TRG_CHECKINGACCOUNT_V1_INSERT AFTER INSERT ON CHECKINGACCOUNT_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE CHECKINGACCOUNT_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TRANSID = NEW.TRANSID;
            END;
DROP TRIGGER IF EXISTS "TRG_CHECKINGACCOUNT_V1_UPDATE";
CREATE TRIGGER TRG_CHECKINGACCOUNT_V1_UPDATE AFTER UPDATE ON CHECKINGACCOUNT_V1
            FOR EACH ROW WHEN ((NEW.ACCOUNTID IS NOT OLD.ACCOUNTID OR NEW.TOACCOUNTID IS NOT OLD.TOACCOUNTID OR NEW.PAYEEID IS NOT OLD.PAYEEID OR NEW.TRANSCODE IS NOT OLD.TRANSCODE OR NEW.TRANSAMOUNT IS NOT OLD.TRANSAMOUNT OR NEW.STATUS IS NOT OLD.STATUS OR NEW.TRANSACTIONNUMBER IS NOT OLD.TRANSACTIONNUMBER OR NEW.NOTES IS NOT OLD.NOTES OR NEW.CATEGID IS NOT OLD.CATEGID OR NEW.TRANSDATE IS NOT OLD.TRANSDATE OR NEW.LASTUPDATEDTIME IS NOT OLD.LASTUPDATEDTIME OR NEW.DELETEDTIME IS NOT OLD.DELETEDTIME OR NEW.FOLLOWUPID IS NOT OLD.FOLLOWUPID OR NEW.TOTRANSAMOUNT IS NOT OLD.TOTRANSAMOUNT OR NEW.COLOR IS NOT OLD.COLOR) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE CHECKINGACCOUNT_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TRANSID = NEW.TRANSID;
            END;
DROP TRIGGER IF EXISTS "TRG_CHECKINGACCOUNT_V1_DELETE";
CREATE TRIGGER TRG_CHECKINGACCOUNT_V1_DELETE AFTER DELETE ON CHECKINGACCOUNT_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('CHECKINGACCOUNT_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_BILLSDEPOSITS_V1_INSERT";
CREATE TRIGGER TRG_BILLSDEPOSITS_V1_INSERT AFTER INSERT ON BILLSDEPOSITS_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE BILLSDEPOSITS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE BDID = NEW.BDID;
            END;
DROP TRIGGER IF EXISTS "TRG_BILLSDEPOSITS_V1_UPDATE";
CREATE TRIGGER TRG_BILLSDEPOSITS_V1_UPDATE AFTER UPDATE ON BILLSDEPOSITS_V1
            FOR EACH ROW WHEN ((NEW.ACCOUNTID IS NOT OLD.ACCOUNTID OR NEW.TOACCOUNTID IS NOT OLD.TOACCOUNTID OR NEW.PAYEEID IS NOT OLD.PAYEEID OR NEW.TRANSCODE IS NOT OLD.TRANSCODE OR NEW.TRANSAMOUNT IS NOT OLD.TRANSAMOUNT OR NEW.STATUS IS NOT OLD.STATUS OR NEW.TRANSACTIONNUMBER IS NOT OLD.TRANSACTIONNUMBER OR NEW.NOTES IS NOT OLD.NOTES OR NEW.CATEGID IS NOT OLD.CATEGID OR NEW.TRANSDATE IS NOT OLD.TRANSDATE OR NEW.FOLLOWUPID IS NOT OLD.FOLLOWUPID OR NEW.TOTRANSAMOUNT IS NOT OLD.TOTRANSAMOUNT OR NEW.REPEATS IS NOT OLD.REPEATS OR NEW.NEXTOCCURRENCEDATE IS NOT OLD.NEXTOCCURRENCEDATE OR NEW.NUMOCCURRENCES IS NOT OLD.NUMOCCURRENCES OR NEW.COLOR IS NOT OLD.COLOR) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE BILLSDEPOSITS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE BDID = NEW.BDID;
            END;
DROP TRIGGER IF EXISTS "TRG_BILLSDEPOSITS_V1_DELETE";
CREATE TRIGGER TRG_BILLSDEPOSITS_V1_DELETE AFTER DELETE ON BILLSDEPOSITS_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('BILLSDEPOSITS_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_SPLITTRANSACTIONS_V1_INSERT";
CREATE TRIGGER TRG_SPLITTRANSACTIONS_V1_INSERT AFTER INSERT ON SPLITTRANSACTIONS_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE SPLITTRANSACTIONS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE SPLITTRANSID = NEW.SPLITTRANSID;
            END;
DROP TRIGGER IF EXISTS "TRG_SPLITTRANSACTIONS_V1_UPDATE";
CREATE TRIGGER TRG_SPLITTRANSACTIONS_V1_UPDATE AFTER UPDATE ON SPLITTRANSACTIONS_V1
            FOR EACH ROW WHEN ((NEW.TRANSID IS NOT OLD.TRANSID OR NEW.CATEGID IS NOT OLD.CATEGID OR NEW.SPLITTRANSAMOUNT IS NOT OLD.SPLITTRANSAMOUNT OR NEW.NOTES IS NOT OLD.NOTES) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE SPLITTRANSACTIONS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE SPLITTRANSID = NEW.SPLITTRANSID;
            END;
DROP TRIGGER IF EXISTS "TRG_SPLITTRANSACTIONS_V1_DELETE";
CREATE TRIGGER TRG_SPLITTRANSACTIONS_V1_DELETE AFTER DELETE ON SPLITTRANSACTIONS_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('SPLITTRANSACTIONS_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETYEAR_V1_INSERT";
CREATE TRIGGER TRG_BUDGETYEAR_V1_INSERT AFTER INSERT ON BUDGETYEAR_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE BUDGETYEAR_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE BUDGETYEARID = NEW.BUDGETYEARID;
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETYEAR_V1_UPDATE";
CREATE TRIGGER TRG_BUDGETYEAR_V1_UPDATE AFTER UPDATE ON BUDGETYEAR_V1
            FOR EACH ROW WHEN ((NEW.BUDGETYEARNAME IS NOT OLD.BUDGETYEARNAME) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE BUDGETYEAR_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE BUDGETYEARID = NEW.BUDGETYEARID;
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETYEAR_V1_DELETE";
CREATE TRIGGER TRG_BUDGETYEAR_V1_DELETE AFTER DELETE ON BUDGETYEAR_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('BUDGETYEAR_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETTABLE_V1_INSERT";
CREATE TRIGGER TRG_BUDGETTABLE_V1_INSERT AFTER INSERT ON BUDGETTABLE_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE BUDGETTABLE_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE BUDGETENTRYID = NEW.BUDGETENTRYID;
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETTABLE_V1_UPDATE";
CREATE TRIGGER TRG_BUDGETTABLE_V1_UPDATE AFTER UPDATE ON BUDGETTABLE_V1
            FOR EACH ROW WHEN ((NEW.BUDGETYEARID IS NOT OLD.BUDGETYEARID OR NEW.CATEGID IS NOT OLD.CATEGID OR NEW.PERIOD IS NOT OLD.PERIOD OR NEW.AMOUNT IS NOT OLD.AMOUNT OR NEW.NOTES IS NOT OLD.NOTES OR NEW.ACTIVE IS NOT OLD.ACTIVE) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE BUDGETTABLE_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE BUDGETENTRYID = NEW.BUDGETENTRYID;
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETTABLE_V1_DELETE";
CREATE TRIGGER TRG_BUDGETTABLE_V1_DELETE AFTER DELETE ON BUDGETTABLE_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('BUDGETTABLE_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETSPLITTRANSACTIONS_V1_INSERT";
CREATE TRIGGER TRG_BUDGETSPLITTRANSACTIONS_V1_INSERT AFTER INSERT ON BUDGETSPLITTRANSACTIONS_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE BUDGETSPLITTRANSACTIONS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE SPLITTRANSID = NEW.SPLITTRANSID;
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETSPLITTRANSACTIONS_V1_UPDATE";
CREATE TRIGGER TRG_BUDGETSPLITTRANSACTIONS_V1_UPDATE AFTER UPDATE ON BUDGETSPLITTRANSACTIONS_V1
            FOR EACH ROW WHEN ((NEW.TRANSID IS NOT OLD.TRANSID OR NEW.CATEGID IS NOT OLD.CATEGID OR NEW.SPLITTRANSAMOUNT IS NOT OLD.SPLITTRANSAMOUNT OR NEW.NOTES IS NOT OLD.NOTES) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE BUDGETSPLITTRANSACTIONS_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE SPLITTRANSID = NEW.SPLITTRANSID;
            END;
DROP TRIGGER IF EXISTS "TRG_BUDGETSPLITTRANSACTIONS_V1_DELETE";
CREATE TRIGGER TRG_BUDGETSPLITTRANSACTIONS_V1_DELETE AFTER DELETE ON BUDGETSPLITTRANSACTIONS_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('BUDGETSPLITTRANSACTIONS_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_CURRENCYHISTORY_V1_INSERT";
CREATE TRIGGER TRG_CURRENCYHISTORY_V1_INSERT AFTER INSERT ON CURRENCYHISTORY_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE CURRENCYHISTORY_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE CURRHISTID = NEW.CURRHISTID;
            END;
DROP TRIGGER IF EXISTS "TRG_CURRENCYHISTORY_V1_UPDATE";
CREATE TRIGGER TRG_CURRENCYHISTORY_V1_UPDATE AFTER UPDATE ON CURRENCYHISTORY_V1
            FOR EACH ROW WHEN ((NEW.CURRENCYID IS NOT OLD.CURRENCYID OR NEW.CURRDATE IS NOT OLD.CURRDATE OR NEW.CURRVALUE IS NOT OLD.CURRVALUE OR NEW.CURRUPDTYPE IS NOT OLD.CURRUPDTYPE) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE CURRENCYHISTORY_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE CURRHISTID = NEW.CURRHISTID;
            END;
DROP TRIGGER IF EXISTS "TRG_CURRENCYHISTORY_V1_DELETE";
CREATE TRIGGER TRG_CURRENCYHISTORY_V1_DELETE AFTER DELETE ON CURRENCYHISTORY_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('CURRENCYHISTORY_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_STOCKHISTORY_V1_INSERT";
CREATE TRIGGER TRG_STOCKHISTORY_V1_INSERT AFTER INSERT ON STOCKHISTORY_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE STOCKHISTORY_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE HISTID = NEW.HISTID;
            END;
DROP TRIGGER IF EXISTS "TRG_STOCKHISTORY_V1_UPDATE";
CREATE TRIGGER TRG_STOCKHISTORY_V1_UPDATE AFTER UPDATE ON STOCKHISTORY_V1
            FOR EACH ROW WHEN ((NEW.SYMBOL IS NOT OLD.SYMBOL OR NEW.DATE IS NOT OLD.DATE OR NEW.VALUE IS NOT OLD.VALUE OR NEW.UPDTYPE IS NOT OLD.UPDTYPE) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE STOCKHISTORY_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE HISTID = NEW.HISTID;
            END;
DROP TRIGGER IF EXISTS "TRG_STOCKHISTORY_V1_DELETE";
CREATE TRIGGER TRG_STOCKHISTORY_V1_DELETE AFTER DELETE ON STOCKHISTORY_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('STOCKHISTORY_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_ATTACHMENT_V1_INSERT";
CREATE TRIGGER TRG_ATTACHMENT_V1_INSERT AFTER INSERT ON ATTACHMENT_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE ATTACHMENT_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE ATTACHMENTID = NEW.ATTACHMENTID;
            END;
DROP TRIGGER IF EXISTS "TRG_ATTACHMENT_V1_UPDATE";
CREATE TRIGGER TRG_ATTACHMENT_V1_UPDATE AFTER UPDATE ON ATTACHMENT_V1
            FOR EACH ROW WHEN ((NEW.REFTYPE IS NOT OLD.REFTYPE OR NEW.REFID IS NOT OLD.REFID OR NEW.DESCRIPTION IS NOT OLD.DESCRIPTION OR NEW.FILENAME IS NOT OLD.FILENAME) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE ATTACHMENT_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE ATTACHMENTID = NEW.ATTACHMENTID;
            END;
DROP TRIGGER IF EXISTS "TRG_ATTACHMENT_V1_DELETE";
CREATE TRIGGER TRG_ATTACHMENT_V1_DELETE AFTER DELETE ON ATTACHMENT_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('ATTACHMENT_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_TAGLINK_V1_INSERT";
CREATE TRIGGER TRG_TAGLINK_V1_INSERT AFTER INSERT ON TAGLINK_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE TAGLINK_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TAGLINKID = NEW.TAGLINKID;
            END;
DROP TRIGGER IF EXISTS "TRG_TAGLINK_V1_UPDATE";
CREATE TRIGGER TRG_TAGLINK_V1_UPDATE AFTER UPDATE ON TAGLINK_V1
            FOR EACH ROW WHEN ((NEW.REFTYPE IS NOT OLD.REFTYPE OR NEW.REFID IS NOT OLD.REFID OR NEW.TAGID IS NOT OLD.TAGID) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE TAGLINK_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TAGLINKID = NEW.TAGLINKID;
            END;
DROP TRIGGER IF EXISTS "TRG_TAGLINK_V1_DELETE";
CREATE TRIGGER TRG_TAGLINK_V1_DELETE AFTER DELETE ON TAGLINK_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('TAGLINK_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_TRANSLINK_V1_INSERT";
CREATE TRIGGER TRG_TRANSLINK_V1_INSERT AFTER INSERT ON TRANSLINK_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE TRANSLINK_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TRANSLINKID = NEW.TRANSLINKID;
            END;
DROP TRIGGER IF EXISTS "TRG_TRANSLINK_V1_UPDATE";
CREATE TRIGGER TRG_TRANSLINK_V1_UPDATE AFTER UPDATE ON TRANSLINK_V1
            FOR EACH ROW WHEN ((NEW.CHECKINGACCOUNTID IS NOT OLD.CHECKINGACCOUNTID OR NEW.LINKTYPE IS NOT OLD.LINKTYPE OR NEW.LINKRECORDID IS NOT OLD.LINKRECORDID) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE TRANSLINK_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE TRANSLINKID = NEW.TRANSLINKID;
            END;
DROP TRIGGER IF EXISTS "TRG_TRANSLINK_V1_DELETE";
CREATE TRIGGER TRG_TRANSLINK_V1_DELETE AFTER DELETE ON TRANSLINK_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('TRANSLINK_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_SHAREINFO_V1_INSERT";
CREATE TRIGGER TRG_SHAREINFO_V1_INSERT AFTER INSERT ON SHAREINFO_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE SHAREINFO_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE SHAREINFOID = NEW.SHAREINFOID;
            END;
DROP TRIGGER IF EXISTS "TRG_SHAREINFO_V1_UPDATE";
CREATE TRIGGER TRG_SHAREINFO_V1_UPDATE AFTER UPDATE ON SHAREINFO_V1
            FOR EACH ROW WHEN ((NEW.CHECKINGACCOUNTID IS NOT OLD.CHECKINGACCOUNTID OR NEW.SHARENUMBER IS NOT OLD.SHARENUMBER OR NEW.SHAREPRICE IS NOT OLD.SHAREPRICE OR NEW.SHARECOMMISSION IS NOT OLD.SHARECOMMISSION OR NEW.SHARELOT IS NOT OLD.SHARELOT) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE SHAREINFO_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE SHAREINFOID = NEW.SHAREINFOID;
            END;
DROP TRIGGER IF EXISTS "TRG_SHAREINFO_V1_DELETE";
CREATE TRIGGER TRG_SHAREINFO_V1_DELETE AFTER DELETE ON SHAREINFO_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('SHAREINFO_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_REPORT_V1_INSERT";
CREATE TRIGGER TRG_REPORT_V1_INSERT AFTER INSERT ON REPORT_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE REPORT_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE REPORTID = NEW.REPORTID;
            END;
DROP TRIGGER IF EXISTS "TRG_REPORT_V1_UPDATE";
CREATE TRIGGER TRG_REPORT_V1_UPDATE AFTER UPDATE ON REPORT_V1
            FOR EACH ROW WHEN ((NEW.REPORTNAME IS NOT OLD.REPORTNAME OR NEW.GROUPNAME IS NOT OLD.GROUPNAME OR NEW.ACTIVE IS NOT OLD.ACTIVE OR NEW.SQLCONTENT IS NOT OLD.SQLCONTENT OR NEW.LUACONTENT IS NOT OLD.LUACONTENT OR NEW.TEMPLATECONTENT IS NOT OLD.TEMPLATECONTENT OR NEW.DESCRIPTION IS NOT OLD.DESCRIPTION) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE REPORT_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE REPORTID = NEW.REPORTID;
            END;
DROP TRIGGER IF EXISTS "TRG_REPORT_V1_DELETE";
CREATE TRIGGER TRG_REPORT_V1_DELETE AFTER DELETE ON REPORT_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('REPORT_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_CUSTOMFIELD_V1_INSERT";
CREATE TRIGGER TRG_CUSTOMFIELD_V1_INSERT AFTER INSERT ON CUSTOMFIELD_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE CUSTOMFIELD_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE FIELDID = NEW.FIELDID;
            END;
DROP TRIGGER IF EXISTS "TRG_CUSTOMFIELD_V1_UPDATE";
CREATE TRIGGER TRG_CUSTOMFIELD_V1_UPDATE AFTER UPDATE ON CUSTOMFIELD_V1
            FOR EACH ROW WHEN ((NEW.REFTYPE IS NOT OLD.REFTYPE OR NEW.DESCRIPTION IS NOT OLD.DESCRIPTION OR NEW.TYPE IS NOT OLD.TYPE OR NEW.PROPERTIES IS NOT OLD.PROPERTIES) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE CUSTOMFIELD_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE FIELDID = NEW.FIELDID;
            END;
DROP TRIGGER IF EXISTS "TRG_CUSTOMFIELD_V1_DELETE";
CREATE TRIGGER TRG_CUSTOMFIELD_V1_DELETE AFTER DELETE ON CUSTOMFIELD_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('CUSTOMFIELD_V1', OLD.pb_id);
            END;
DROP TRIGGER IF EXISTS "TRG_CUSTOMFIELDDATA_V1_INSERT";
CREATE TRIGGER TRG_CUSTOMFIELDDATA_V1_INSERT AFTER INSERT ON CUSTOMFIELDDATA_V1
            FOR EACH ROW WHEN NEW.pb_is_dirty IS NOT 2
            BEGIN
                UPDATE CUSTOMFIELDDATA_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE FIELDATADID = NEW.FIELDATADID;
            END;
DROP TRIGGER IF EXISTS "TRG_CUSTOMFIELDDATA_V1_UPDATE";
CREATE TRIGGER TRG_CUSTOMFIELDDATA_V1_UPDATE AFTER UPDATE ON CUSTOMFIELDDATA_V1
            FOR EACH ROW WHEN ((NEW.FIELDID IS NOT OLD.FIELDID OR NEW.REFID IS NOT OLD.REFID OR NEW.CONTENT IS NOT OLD.CONTENT) AND NEW.pb_is_dirty IS NOT 2)
            BEGIN
                UPDATE CUSTOMFIELDDATA_V1 SET pb_is_dirty = 1, pb_updated_at = STRFTIME('%Y-%m-%dT%H:%M:%SZ', 'NOW')
                WHERE FIELDATADID = NEW.FIELDATADID;
            END;
DROP TRIGGER IF EXISTS "TRG_CUSTOMFIELDDATA_V1_DELETE";
CREATE TRIGGER TRG_CUSTOMFIELDDATA_V1_DELETE AFTER DELETE ON CUSTOMFIELDDATA_V1
            FOR EACH ROW WHEN OLD.pb_id IS NOT NULL AND OLD.pb_id != ''
            BEGIN
                INSERT INTO pb_DELETED_RECORDS_LOG (table_name, pb_id) VALUES ('CUSTOMFIELDDATA_V1', OLD.pb_id);
            END;
PRAGMA user_version = 21;