SELECT	CATEGORY_V1.CATEGID,
			CATEGORY_V1.CATEGNAME,
			-1 AS SUBCATEGID,
			NULL AS SUBCATEGNAME,
			CATEGORY_V1.CATEGNAME AS CATEGSUBNAME
FROM		CATEGORY_V1
			
UNION
		
SELECT	CATEGORY_V1.CATEGID,
			CATEGORY_V1.CATEGNAME,
			SUBCATEGORY_V1.SUBCATEGID,
			SUBCATEGORY_V1.SUBCATEGNAME,
			CATEGORY_V1.CATEGNAME || CASE WHEN SUBCATEGORY_V1.SUBCATEGNAME IS NOT NULL THEN ' : ' || SUBCATEGORY_V1.SUBCATEGNAME ELSE '' END AS CATEGSUBNAME
FROM 		CATEGORY_V1 INNER JOIN SUBCATEGORY_V1 ON CATEGORY_V1.CATEGID = SUBCATEGORY_V1.CATEGID
